services:
  gateway:
    tty: true
    build:
      context: ./gateway
      dockerfile: Dockerfile
    volumes:
      - ./gateway:/app
    ports:
      - '8080:8080'
    networks:
      - local_network

#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    ports:
#      - '8001:8001'

  database:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - local_network

volumes:
  pgdata:

networks:
  local_network: {}