services:
  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    volumes:
      - ./gateway:/app
    ports:
      - '8080:8080'
    networks:
      - local_network

  user-backend:
    container_name: user-backend
    build:
      context: ./userbackend
      dockerfile: Dockerfile
    volumes:
      - ./userbackend:/app
    ports:
      - '8081:8081'
    networks:
      - local_network

  database:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - local_network

volumes:
  pgdata:

networks:
  local_network: {}